[package]
name = "wasmtime-ruby"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cranelift-codegen = "0.40.0"
cranelift-native = "0.40.0"
lazy_static = "1.4.0"
rutie = "0.7.0"
wasmtime-interface-types = "0.3.0"
wasmtime-jit = "0.3.0"
