name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - run: bundle install
      - run: rake build
      - run: rake spec
      - run: gem build wasmtime.gemspec
      - uses: actions/upload-artifact@v2
        with:
          name: gem
          path: wasmtime-*.gem
